# Default Fields for places api calls

default_search_fields: [
  "displayName",
  "id",
  "location"
]

default_nearby_fields: [
  "displayName",
  "id",
  "location"
]

default_places_fields: [
    "displayName",
    "formattedAddress",
    "location",
    "reviews",
    "photos",
    "regularOpeningHours",
    "websiteUri",
    "internationalPhoneNumber",
    "priceLevel",
    "serves_breakfast",
    "outdoor_seating",
    "reservable"
]
